---
name: nauticML

channels:
  - conda-forge

dependencies:
  - python=3.11
  # cannot install tensorflow using pip, it is not compatible with cuda drivers
  - tensorflow=2.12
  - nvidia/label/cuda-11.8.0::cuda-nvcc
  - nvidia/label/cuda-11.8.0::cuda-toolkit
  - matplotlib=3.7
  - seaborn=0.13.2
  - numpy<1.24
  - pip
  - pip:
      - -r requirements.txt

